### PR TITLE
Chang-Refsdal

### PR DESCRIPTION
**Pull request by alpv95**
# What
Additional parameters `convergence_K` (positive scalar) and `shear_G` (complex) define an external mass sheet on top of a point lens. They can be optionally defined and create a more complex caustic structure, with `shear_G` creating up to 4 images of the source.

# Why 
Stars embedded in a more diffuse mass distribution like a galaxy can lens extragalactic objects: Nature, Volume 282, Issue 5739, pp. 561-564 (1979). The diffuse external mass can be modelled as perturbation to the standard point source formalism.

# How
I added an additional method to `magnificationcurve.py`, `method='point_source_with_shear'`. `convergence_K`, `shear_G` and `alpha` must be defined for this to work, since the external mass sheet caustic structure is no longer necessarily symmetric.
Additionally, I added new class file `causticspoint.py` to draw the resulting caustics. Example 21 plots the results, and some unit tests have been added.

Chang-refsdal currently only works with a point source, but it could be relatively straightforward to extend to the case of a finite source by using some of the approximation functions defined for the binary lens.

### CODE REVIEW

**Comment by rpoleski** [comment]
I've reviewed the code, made some minor changes and prepared a list of tasks to be done:

- [ ] Is alpha required if either convergence or shear are equal to 0? - Lawrence
- [ ] Does `convergence_K` have to be positive? - Lawrence
- [ ] Check example 22; add it to examples list - Radek
- [ ] Why "from cmath import sqrt" and not "from math ..." in causticspoint.py? - Lawrence
- [ ] Move 'point_source_with_shear' to the end of MagnificationCurve.get_point_lens_magnification(), add docstrings about it, add "[selection]" there
- [ ] Double check changes in ModelParameters._check_valid_combination_1_source_binary_lens() - in particular `alpha`
- [ ] Make sure that d_alpha_d_t is not defined for single lens model
- [ ] PEP8 in changed files
- [ ] test_Caustics.py: 1) uncomment test_point_caustic(), 2) move to new file
- [ ] test_MagnificationCurve.py - do we need `set_magnification_methods()` in the last test?
- [ ] update `__version__`, run sphinx

**Comment by alpv95** [comment]
>

**Comment by rpoleski** [comment]
Ok. We have a point that requires some more thinking. We definitely don't want the user to define unnecessary parameters, i.e., alpha for shear = 0 case. 

CITE:
I can make this work if I can pass full dictionary: _check_valid_combination_1_source_standard(self, keys) -> _check_valid_combination_1_source_standard(self, parameters)

I would make `_check_valid_combination_1_source_standard(self, keys, shear_value=0.)`.
I note that in that case shear should not be defined, rather than set to 0.
I'll write appropriate automated tests and then change the code until it works :)

**Comment by rpoleski** [comment]
Lawrence, could you please check my recent commit with tests of parameters? Can you confirm that these first batch of tests defines a model and the other batch does not define a model? Currently 6 tests pass and 3 fail.

**Comment by alpv95** [comment]
I've fixed modelparameters.py so that alpha only has to be defined when shear_G is non-zero. However I'm not sure whether all 9 of the tests you have made should pass:

* I think it might be a good idea to have the user always define convergence and shear together, even if one of them is zero. This keeps the user aware of all of the available mass sheet parameters and keeps implications of not defining one explicit.
*  I'm not sure defining alpha when it is unnecessary should raise an error. This wasn't implemented for standard point lens so why should it be implemented for point lens with shear?

**Comment by rpoleski** [comment]
Ad. 1. We don't want the user to set `s=0` and `q=0` for single lenses, or `dalpha_dt=0` for binary lenses. Hence, we also don't want force them to define all mass sheet parameters. 
Ad. 2. I've just checked that if you define `t_0`, `u_0`, `t_E`, and `alpha`, then the error is raised - as expected.

**Comment by rpoleski** [comment]
New question: In `PointLens.get_pspl_with_shear_magnification()` there is a check `if not np.isnan(det):` - is it meant to handle `root = 0.` case? If so, then I would change it to:

```python
for root in roots:
    if root == 0.:
        continue
    mag += 1. / abs(...)
```

**Comment by rpoleski** [comment]
I've realized the tests were not correct. @alpv95  - can you please check current version of `tests/test_temp.py` and confirm that it is OK (assuming that the user doesn't have to define K and G together)?

**Comment by alpv95** [comment]
OK, now K and G can be defined individually, and alpha can only be defined when G is non-zero. I allowed this by adding default zero values when K and G are passed to functions that use them.
I also changed the root code as you suggested, you're right this is a much better solution that avoids warnings.

**Comment by rpoleski** [comment]
I must admit that this PR gave me a chance to review parts of the code that I have not reviewed in a long time. Thanks!

**Comment by rpoleski** [comment]
After long silence I'm preparing updated list of tasks:

- [ ] Check example 22; add it to examples list - Radek
- [ ] Move 'point_source_with_shear' to the end of MagnificationCurve.get_point_lens_magnification(), add docstrings about it, add "[selection]" there
- [ ] Make sure that d_alpha_d_t is not defined for single lens model
- [ ] PEP8 in changed files
- [ ] test_Caustics.py: 1) uncomment test_point_caustic(), 2) move to new file
- [ ] make sure that chi2 gradient calculations are forbidden for PSPL with mass sheet
- [ ] update `__version__`, run sphinx

**Comment by rpoleski** [comment]
Today I've solved first 3 points above and modified the list.
The remaining tasks are all relatively simple.

@jenniferyee - can you check changes in functions names etc.?
@alpv95 - we're close to merging!

**Comment by rpoleski** [comment]
@alpv95 Did you ever get error of magnification < 1? I'd like to use it for tests.

**Comment by rpoleski** [comment]
Point 5 above is considered solved for now. The error message for magnification < 1 is not tested because at this point I don't have example input.

**Comment by rpoleski** [comment]
Only confilct in `magnificationcurve.py` requires some thinking. Other ones are simple.

**Comment by rpoleski** [comment]
Can be merged at this point. Sphinx should be run after the merge.

**Pull request merged**
