### PR TITLE
Issue #94: proposed 1L2S get_trajectory bug fixes

### PR DESCRIPTION
**Pull request by jenniferyee**
Proposed bug fixes for Model.get_trajectory() and FitData.get_dataset_trajectory(). Also updated Ex 17 to include plotting of 1L2S trajectory figure and added unittests for Model.get_trajectory() and FitData.get_dataset_trajectory(). These unit tests currently fail. We need to update the reference files to include trajectory X, Y, first.

### CODE REVIEW

**Comment by jenniferyee** [comment]
Specifically, what is needed:

SAMPLE_FILE_03_REF = join(dir_2, 'ob140939_Spitzer_ref_v1.dat') 

Needs columns ADDED for Spitzer source trajectory X and Y positions as in

```
ref_Spitzer = np.loadtxt(SAMPLE_FILE_03_REF, unpack=True)
ratio_x = trajectory.x / ref_Spitzer[6]
ratio_y = trajectory.y / ref_Spitzer[7]
```

**Comment by rpoleski** [comment]
@jenniferyee I would just test against values returned by current code - are you ok with that? It'll take me relatively long to get them from independent code like sfit.

**Comment by rpoleski** [comment]
Without running the code, I see that `Model.get_trajectory()` should have `satellite_skycoord` keyword describe. It's a new aspect of API, so we should change the version to 2.19.

**Review by rpoleski — CHANGES_REQUESTED** [review]
`Model.get_trajectory()` docstrings need updates: 

1. `satellite_skycoord` has to be described
2. returned type for binary source has to be given.

Everything else is OK.

**Comment by jenniferyee** [comment]
HOORAY!
--------------------------------------------------------------
Dr. Jennifer C. Yee
(she/her)

Office: P-341
Center for Astrophysics | Harvard & Smithsonian
60 Garden St, MS-15
Cambridge, MA 02138
--------------------------------------------------------------

**Pull request merged**
