### PR TITLE
Init Github actions CI python-app.yml

### PR DESCRIPTION
**Pull request by justi**

### CODE REVIEW

**Comment by rpoleski** [comment]
Build failed in a use case 11. I've corrected that use case, but in general we don't want to test use cases as this is our "make a wish" code.

**Comment by justi** [comment]
@rpoleski could you commit your changes here? We will check the pipeline with the fixed code. The tests don run yet because syntax errors are here. After the lint check it pytest will be called.

**Comment by rpoleski** [comment]
Right! It makes sense to commit here :)

**Comment by justi** [comment]
@rpoleski looks like some code changes from master cause 2 new fails

**Comment by rpoleski** [comment]
I bet the CI is installing some different version than the code here. In this branch line 59 of `magnificationcurve.py` says `TypeError` but the CI pytest says `ValueError` (line 57 in "Test with pytest" section).

**Comment by justi** [comment]
Thats wired. But when I fetched this branch and run pytest, the same fails appear.

**Comment by justi** [comment]
Ok, I see where the problem is. When I use 'pip install MulensModel' the library is installed from the master branch. From this time pytest runs on the library, not a local repo code.

**Comment by rpoleski** [comment]
I don't get it - I've updated the PyPI version in the meantime by making a release. I don't know what version of MM is installed here. Any ideas how to correct it?

**Comment by rpoleski** [comment]
No CI is completed. @justi  what is the next step? Should I merge it?
It would be good if you could configure also a run of `coverage`, so that we could inspect results easily.

**Comment by justi** [comment]
At this moment I see the CI passed, good job :) I can check how to configure test coverage.

**Comment by rpoleski** [comment]
Sorry for distraction - the last two commits should be to master branch.

**Pull request merged**
