### PR TITLE
UltraNest fitting method added to example_16

### PR DESCRIPTION
**Pull request by rapoliveira**
Implementation of the UltraNest fitting method to example_16, using several functions similar to MultiNest.
There are no required parameters to run, but some optional parameters that may be useful in some cases were added.

Commented lines were added to `ob03235_2_full.yaml` file, but a YAML file specific for the application of UltraNest to the same data is also included. Comments are welcome!

My impression is that the algorithm was not very effective in finding the solution if a large parameter space is given, specially for cases with more parameters or complex magnifications, e.g. binary lens.

### CODE REVIEW

**Comment by rpoleski** [comment]
Generally, it looks OK. I have minor comments listed below. The last item is most important and time consuming. If you don't want to work on it, then just make it illegal to combine UN and Cassan08 :)

1. line 384 - Add new option at the end, so that existing codes that don't use kwargs are not broken
2. line 561 - I don't get the comment - please correct the code or change comment.
3. line 569 - Please make it defensive, i.e., make it work even if 'Ultranest' is provided instead of 'UltraNest'.
4. line 646 - Spelling to be corrected.
5. line 647 - Why cython?
6. lines 1364-1379 - I don't get it. Seems for me that `settings` should be a copy of an existing dict because it's changed at the end.
7. line 2567 - For me looks like a feature that is not documented at the top of the class.
8. line 2656 - Yes, there should be a check: if the parameterization is based on Cassan then the parameters should correspond to existing trajectory (i.e., both crossings are on the same caustic). 

Note to @rpoleski - the last item shows that condition in line 2597 should be corrected.

**Comment by rpoleski** [comment]
I've relaized that nobody complaint about this code failing on Cassan08 with MultiNest so solving item no. 8 and note below it is an additional ehancement, not a requirement.

**Comment by rpoleski** [comment]
9. In yaml file and in the code you added `source_flux` and `blending_flux` as derived parameters. First, it's meaning is clear only for single dataset cases. Second, it's different than `flux_s_1` and `flux_b_1` used in this code currently. Hence, please change the labels to `flux_X_N`.

**Comment by rapoliveira** [comment]
@rpoleski Just a note that I will implement the prior in UltraNest this week, before the merge.

**Comment by rpoleski** [comment]
One remaining aspect - do we need `_transform_unit_cube_UltraNest()` or it's enough to call `_transform_unit_cube()` when using both MN and UN?

**Comment by rapoliveira** [comment]
@rpoleski my last five commits include:
- single transform function for MultiNest and UltraNest
- implemented priors for UltraNest: negative_blending_flux_sigma_mag and t_E
- Minor fixes (np.append, parse posterior error, yaml files)
- Separate function to check UltraNest inputs, including the names of the derived parameters. This last one required to call self._parse_fitting_parameters() after self._event is created. I checked that it doesn't affect the results of any examples

Please let me know if I missed anything from our discussions.

**Pull request merged**
