### PR TITLE
Add coverage metric

### PR DESCRIPTION
**Pull request by justi**

### CODE REVIEW

**Comment by rpoleski** [comment]
I've found 2 examples of coverage badges that additionally link to websites that gives more details:

- [https://github.com/dfm/emcee](https://github.com/dfm/emcee) -> [https://coveralls.io/github/dfm/emcee?branch=main](https://coveralls.io/github/dfm/emcee?branch=main)
- [https://github.com/astropy/astropy](https://github.com/astropy/astropy) -> [https://app.codecov.io/gh/astropy/astropy](https://app.codecov.io/gh/astropy/astropy)

Can you add one of these badges? I don't have a preference which one is easier to setup or works better.

**Comment by rpoleski** [comment]
Should it be merged now?

**Comment by justi** [comment]
> Should it be merged now?

yes :)

**Comment by rpoleski** [comment]
Can we remove files and directories that were added, but are also listed in `.gitignore`:
 - `.idea/workspace.xml`
 - `coverage.xml`
 - `source/MulensModel.egg-info/`
 - `source/MulensModel/*.so`
?

**Comment by rpoleski** [comment]
Thank for removing useless files not conected to this PR (`docs/_sources/`) - they were not updated in 2 years!

**Pull request merged**
